runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /
    static_files: dist/weather-search/browser/index.html
    upload: dist/weather-search/browser/index.html

  - url: /(.*)
    static_files: dist/weather-search/browser/\1
    upload: dist/weather-search/browser/(.*)

  - url: /.*
    static_files: dist/weather-search/browser/index.html
    upload: dist/weather-search/browser/index.html
